// Mocks generated by Mockito 5.2.0 from annotations
// in tdd_flutter_graphql/test/src/modules/characters/domain/usecases/fetch_paginated_characters_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_flutter_graphql/src/modules/characters/data/repo/interface/paginated_characters_repo.dart'
    as _i3;
import 'package:tdd_flutter_graphql/src/modules/characters/domain/entities/character_entity.dart'
    as _i5;
import 'package:tdd_flutter_graphql/src/modules/common/data/models/paginated.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePaginated_0<T extends Object> extends _i1.Fake
    implements _i2.Paginated<T> {}

/// A class which mocks [PaginatedCharactersRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaginatedCharactersRepo extends _i1.Mock
    implements _i3.PaginatedCharactersRepo {
  MockPaginatedCharactersRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Paginated<List<_i5.CharacterEntity>>> fetchCharacters(
          int? page) =>
      (super.noSuchMethod(Invocation.method(#fetchCharacters, [page]),
          returnValue: Future<_i2.Paginated<List<_i5.CharacterEntity>>>.value(
              _FakePaginated_0<List<_i5.CharacterEntity>>())) as _i4
          .Future<_i2.Paginated<List<_i5.CharacterEntity>>>);
}
